package com.belote.client.Game.Rounds;

public enum Contract {
    SPADES, DIAMONDS, HEARTS, CLUBS, NO_TRUMPS, ALL_TRUMPS, PASS,
    SPADES_DOUBLE, DIAMONDS_DOUBLE, HEARTS_DOUBLE, CLUBS_DOUBLE, NO_TRUMPS_DOUBLE, ALL_TRUMPS_DOUBLE,
    SPADES_REDOUBLE, DIAMONDS_REDOUBLE, HEARTS_REDOUBLE, CLUBS_REDOUBLE, NO_TRUMPS_REDOUBLE, ALL_TRUMPS_REDOUBLE
}
